language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

# Accept licenses manually, workaround:
# https://github.com/travis-ci/travis-ci/issues/8874
before_install:
  - yes | sdkmanager "tools"
  - yes | sdkmanager "platform-tools"
  - yes | sdkmanager "build-tools;27.0.3"
  - yes | sdkmanager "platforms;android-27"

script: 
    - ./gradlew build

deploy:
  skip_cleanup: true
  provider: script
  script:
    - ./gradlew build bintrayUpload --info
  on:
    branches:
      only:
        - master
        - feature/test-build-0.9.9
